### ISSUE TITLE
PWM_SHAKER question

### ISSUE THREAD

**Issue by baritonomarchetto** [njz3/vJoyIOFeederWithFFB#13]
Hello Benjamin,

may I ask: which pin is PWM rumble signal sent when PWM_SHAKER is choosed: is it arduino pin 22 (driverboard first bit)?

Thanks

**Comment by njz3** [comment]
Hi,
It is the first PWM analog output pin that is usually mapped to D9 on a Leonardo or a Mega2560.

**Comment by njz3** [comment]
I have seen that you have a JVS project to replace the Sega IO board.
Do you think I can implement the JVS protocol with a USB to RS485 adapter directly plug to a PC to drive the Sega IO board and avoid an Arduino ? (this would be for a F355 twin cab where I only want to swap the stack).

**Comment by baritonomarchetto** [comment]
I am sorry, but I have no idea: I left the output handling out of the project because it's out of my capabilities. I am no expert in that field.
That replacement I/O board only emulates a joystick, but has not the ability to receive game outputs.
