### ISSUE TITLE
Trial Period Expired - MEGA not responding for some seconds

### ISSUE THREAD

**Issue by baritonomarchetto** [njz3/vJoyIOFeederWithFFB#14]
Hello Benjamin,

I was asking myself if that "trial period expired" message that pops up in the BFF console could affect the game experience (apart from the windows notifications) and now that I have spent some valuable time with your software I can answer myself: yes it does :)

When it pops up makes inputs not responsive for about 5 seconds, right? Is it how it is intended to work? 

Could it be made less intrusive eventually? I know that you sell license for it (and it's worth it!!), but could you eventually take into consideration disabling some advanced function instead for poorer tinkerers out there :) ?

(how much is a license at today, if I can ask here?)

Thanks for this great piece of software!!

**Comment by njz3** [comment]
Yes the popup also freezes the software for 5sec, but this happen after 15minutes, which is an acceptable trial to test.
For the licence, click on the About button and send an email to me to get more information.
