### ISSUE TITLE
Closing issue

### ISSUE THREAD

**Issue by Tibal51** [njz3/vJoyIOFeederWithFFB#16]
Hey njz3

Sometimes, when the turn-off sequence of the PC and its power-off are badly timed, the Config folder gets corrupted.

Could you please deactivate the Config saving when the main window of BFF is closed please, as there is no parameter in it ?

I hope it will be enough to solve my issue.

Thanks in advance !

**Comment by njz3** [comment]
Should be fixed with 0.6.0.88 by saving the configuration files only when closing a sub-form of the main window.
