### ISSUE TITLE
Nice work - BTS7960 works

### ISSUE THREAD

**Issue by vikbez** [njz3/vJoyIOFeederWithFFB#3]
Thanks A LOT for this;

I was desperately trying to find something to help me convert a trashed GTI Club twin cab.
This works nicely so far; I still have to try and finetune configs to see how well this performs.

I don't think you had in mind to use BTS7960 generic DC motor driver boards but .. it works with your soft+firmware on an arduino leonardo. (I'm using original cabinet DC motors with BTS7960 drivers, as original pcbs are missing)

Thanks again, I will follow this closely.

**Comment by njz3** [comment]
Thanks for your feedback
Actually the soft was first meant to use a H motor driver like yours to drive DC motors. The L620X was the first target. Yours seems similar from a control point of view (pwm, fwd and rev directions).
