### ISSUE TITLE
USB HID PID FFB

### ISSUE THREAD

**Issue by arilink-tech** [njz3/vJoyIOFeederWithFFB#4]
Hello. I’m trying to make an FFB steering wheel. Could you please tell me the relevant knowledge?

**Comment by njz3** [comment]
Hi,
What are you trying to do ? Do you plan to use my vJoy feeder with a custom motor driver ?
Regarding USB HID and PID for FFB, please have a look to https://github.com/njz3/vJoy/tree/master/docs and https://github.com/njz3/vJoyIOFeederWithFFB/blob/master/docs/pid1_01.pdf
