### ISSUE TITLE
What about Rumble?

### ISSUE THREAD

**Issue by baritonomarchetto** [njz3/vJoyIOFeederWithFFB#7]
Hello, first of all thanks for sharing such a nice project but also for spending your time in documenting it.
I know that most of the racing games this hardware/software combination support do not support rumble (they are FF games) but would it be possibile to add some support for Rumble setups? In other words, would it be possibile to include a routine that "translates" FF messages into rumble, i.e. by triggering a rotating motor only when the car goes out of track or collides with another car and ignores all the other FF effects?
Thanks :)

**Comment by njz3** [comment]
I actually added this into the latest version (not public).
It is PWM_SHAKER mode. The Arduino will output a PWM that can be used as a rumble.

**Comment by baritonomarchetto** [comment]
Great!

**Comment by baritonomarchetto** [comment]
Sorry for calling back this old request of mine: is PWM_SHAKER mode pubblic now?

**Comment by njz3** [comment]
It is available in the latest 0.6 binary version, but source will be kept as closed.

**Comment by baritonomarchetto** [comment]
(Benjamin, sorry for bothering you. May I ask why source is closed now? Not that I want to modify or take advantage from it, it's way out of my possibilities, and the exe is more than enought, but it's always a bad news when the development of such a nice project is made unavailable)

**Comment by njz3** [comment]
Reasons are that some part of the 0.6 version contains advanced filtering algorithms (state estimator) and many corrections to the ffb engine that I do not want to disclose, and also I want to restrain people from reselling my work for commercial arcade activities, by at least enforcing them to get a licence for each install so that I know who use the software in this small community.

**Comment by baritonomarchetto** [comment]
Makes sense. Thanks for your answer
